services:
  php-fpm:
    image: php:8.3-fpm
    container_name: php-fpm-test
    ports:
      - "9000:9000"
    volumes:
      - ./www:/var/www/html
      - ./fpm.conf:/usr/local/etc/php-fpm.d/www.conf
    working_dir: /var/www/html
